version: '3.7'

x-debug-settings: &xdebug-settings
  XDEBUG_CLIENT_HOST: ${XDEBUG_CLIENT_HOST}
  XDEBUG_CLIENT_PORT: ${XDEBUG_CLIENT_PORT}
  XDEBUG_MODE: ${XDEBUG_MODE}
  XDEBUG_START_WITH_REQUEST: ${XDEBUG_START_WITH_REQUEST}
  XDEBUG_TRIGGER: ${XDEBUG_TRIGGER}
  XDEBUG_LOG_FILE: ${XDEBUG_LOG_FILE}
  XDEBUG_LOG_LEVEL: ${XDEBUG_LOG_LEVEL}

services:
  app:
    build:
      context: .
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html